server:
  port: 8021
spring:
  #给项目来个名字
  application:
    name: rabbitmq-provider
#配置rabbitMq 服务器
  rabbitmq:
    host: 192.168.1.124
    port: 5672
    username: user
    password: 123456
#虚拟host 可以不设置,使用server默认host
    virtual-host: test
    listener:
      simple:
        acknowledge-mode: manual  #消费者手动执行ack确认
        default-requeue-rejected: false #默认拒绝重回队列
    #RabbitTemplate.ConfirmCallback, RabbitTemplate.ReturnCallback
    publisher-confirms: true
    publisher-returns: true
  redis:
    host: 192.168.0.124
    port: 6379
