server:
      servlet:
            context-path: /mongo
      port: 9001


spring:
      banner:
            location: classpath:banner.txt
      data:
            mongodb:
                  uri: mongodb://192.168.0.107:27017/mytest
  #                mongodb://192.168.0.107:27017,192.168.0.107:27018,192.168.0.107:27019/mytest?connect=replicaSet&slaveOk=true&replicaSet=myrs
#                  mongodb://192.168.0.107:27017/mytest


